import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { TrpcProvider } from './trpc-provider'
import { Toaster } from '@/components/ui/sonner'
import './globals.css'
import './rc-image.scss';

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] })
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.className} antialiased`}>
        <Toaster />
        <TrpcProvider>
          {children}
        </TrpcProvider>
      </body>
    </html>
  )
}
